volumes:
    postgres-alten-shop-vol:

services:
  postgres:
    container_name: alten-shop-db-local-container
    labels:
      org.springframework.boot.service-connection: postgres
    image: "postgres:16"
    environment:
      POSTGRES_USER: "altenshop"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "alten-shop-db-local"
      PGDATA: "/data/postgres"
    volumes:
       - postgres-alten-shop-vol:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped