spring:
  application:
    name:
      alten-shop-demo
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

springdoc:
  swagger-ui: 
    tagsSorter: alpha