spring:
  datasource:
    url: jdbc:postgresql://localhost:5454/alten-shop-db-dev
    username: altenshop
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    
  flyway:
    enabled: false