server:
  port: 8085
spring:
  application:
    name:
      alten-shop-demo
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  docker:
    compose:
      lifecycle-management: start-and-stop

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
