create table app_user (
    id bigint generated by default as identity, 
    email varchar(40) unique, 
    firstname varchar(255), 
    password varchar(255), 
    username varchar(20) unique, 
    primary key (id)
);

create table product (
    id bigint generated by default as identity,
    code varchar(255) not null,
    name varchar(255) not null,
    description varchar(255) not null,
    image varchar(255) not null,
    category varchar(255) not null,
    price numeric(10,2),
    quantity integer,
    internal_reference varchar(255),
    shell_id bigint,
    inventory_status varchar(255) check (inventory_status in ('INSTOCK','LOWSTOCK','OUTOFSTOCK')),
    rating integer,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    primary key (id)
);

create table cart_item (
    id bigint generated by default as identity, 
    quantity integer check (quantity>=1), 
    app_user_id bigint, 
    product_id bigint, 
    primary key (id)
);

create table wishlist_item (
    id bigint generated by default as identity, 
    app_user_id bigint, 
    product_id bigint, 
    primary key (id)
);
